language: generic
services:
  - docker

before_install:
  - docker build  -t valdiz777/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true valdiz777/react-test yarn run test -- --coverage

after_success:
  - docker build -t valdiz777/multi-client ./client
  - docker build -t valdiz777/multi-nginx ./nginx
  - docker build -t valdiz777/multi-server ./server
  - docker build -t valdiz777/multi-worker ./worker

 # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # push to docker hub
  - docker push valdiz777/multi-client
  - docker push valdiz777/multi-nginx 
  - docker push valdiz777/multi-server
  - docker push valdiz777/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-406033701411
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


